# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-06-18 11:52
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import new.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test23',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'test23',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Academic_degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=200, verbose_name='Сокращенное название')),
            ],
            options={
                'verbose_name': 'Ученую степень',
                'verbose_name_plural': 'Ученые степени',
            },
        ),
        migrations.CreateModel(
            name='Branch_science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science', models.CharField(max_length=1300, verbose_name='Наука')),
            ],
            options={
                'verbose_name': 'Отрасль науки',
                'verbose_name_plural': 'Отрасли наук',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1300, verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleconf', models.CharField(max_length=200, verbose_name='Тема конференции')),
                ('textconf', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст')),
                ('date_launch_s', models.CharField(max_length=10, verbose_name='Время проведения конференции с')),
                ('date_launch_po', models.CharField(max_length=10, verbose_name='по')),
                ('srok_podacha', models.CharField(max_length=10, verbose_name='Срок подачи статей и докладов')),
                ('srok_prin_resh_itog', models.CharField(max_length=10, verbose_name='Срок принятия решений по итогам конференции')),
                ('sostav_orgkomitet', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст')),
                ('otmenpublic', models.BooleanField(verbose_name='Снять с публикации')),
                ('created_dateconf', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_dateconf', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания конференции')),
                ('authorconf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организатор конференции')),
                ('branch_science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='new.Branch_science', verbose_name='Отрасль науки')),
            ],
            options={
                'verbose_name': 'Конференцию',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Conference_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlematirial', models.CharField(max_length=140, verbose_name='Заголовок')),
                ('authormatirial2', models.CharField(max_length=340, verbose_name='Автор материала')),
                ('textmaterial', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст')),
                ('message_com', models.TextField(blank=True, max_length=1300, verbose_name='Комментарий администратора')),
                ('file_obj', models.FileField(blank=True, max_length=2500, upload_to=new.models.user_directory_path, verbose_name='Файл для материала')),
                ('otmenpublic', models.BooleanField(verbose_name='Снять с публикации')),
                ('annotation_rus', models.TextField(blank=True, null=True, verbose_name='Аннотация (Rus)')),
                ('annotation_usa', models.TextField(blank=True, null=True, verbose_name='Аннотация (Eng)')),
                ('keywords_rus', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (Rus)')),
                ('keywords_usa', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (Eng)')),
                ('created_datematerial', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_datematerial', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('authormatirial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель материала')),
                ('branch_science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Branch_science', verbose_name='Отрасль науки')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Conference', verbose_name='Материал для конференции')),
            ],
            options={
                'verbose_name': 'Материал для конференции',
                'verbose_name_plural': 'Материалы для конференций',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameconfer', models.CharField(max_length=300, verbose_name='Тема конференции')),
                ('date_launch_s', models.CharField(blank=True, max_length=10, verbose_name='Время проведения конференции с')),
                ('date_launch_po', models.CharField(blank=True, max_length=10, verbose_name='по')),
                ('srok_podacha', models.CharField(blank=True, max_length=10, verbose_name='Срок подачи статей и докладов')),
                ('srok_prin_resh_itog', models.CharField(blank=True, max_length=10, verbose_name='Срок принятия решений по итогам конференции')),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Описание конференции и требования к публикации')),
                ('sostav_orgkomitet', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст')),
                ('message_com', models.TextField(blank=True, max_length=1300, null=True, verbose_name='Комментарий администратора')),
                ('published_contact', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки заявки')),
                ('branch_science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Branch_science', verbose_name='Отрасль науки')),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Заявка на создание конференции',
                'verbose_name_plural': 'Заявки на создание конференций',
            },
        ),
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Foto_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, max_length=2500, upload_to=new.models.user_path, verbose_name='Файл для материала')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=200, verbose_name='Сокращенное название')),
            ],
            options={
                'verbose_name': 'Организацию',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Pol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepole', models.CharField(max_length=200, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=200, verbose_name='Сокращенное название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=300, verbose_name='Секция')),
                ('comentsection', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подробнее')),
                ('confer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='new.Conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Секцию',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Status_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_contact', models.CharField(max_length=300, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Status_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Статус_admin')),
            ],
            options={
                'verbose_name': 'Статус_admin',
                'verbose_name_plural': 'Статусы_admin',
            },
        ),
        migrations.CreateModel(
            name='Status_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Статус_user')),
            ],
            options={
                'verbose_name': 'Статус_user',
                'verbose_name_plural': 'Статусы_user',
            },
        ),
        migrations.CreateModel(
            name='Trebovania_public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trebovania', models.CharField(max_length=1000, verbose_name='Требования к публикации')),
            ],
            options={
                'verbose_name': 'Требование к публикации',
                'verbose_name_plural': 'Требования к публикации',
            },
        ),
        migrations.CreateModel(
            name='Uchenoe_zvanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=200, verbose_name='Сокращенное название')),
            ],
            options={
                'verbose_name': 'Ученое звание',
                'verbose_name_plural': 'Ученые звания',
            },
        ),
        migrations.CreateModel(
            name='User_conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1300, null=True, verbose_name='Описание конференции')),
                ('published_us_confr', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки запроса на добавление в конференцию')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children2', to='new.Conference', verbose_name='Конференция')),
                ('status_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Status_role', verbose_name='Роли конференции')),
                ('status_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Status_user', verbose_name='Статус пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uchconf', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Годы',
            },
        ),
        migrations.AddField(
            model_name='contactform',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Status_contact', verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='contactform',
            name='trebovania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new.Trebovania_public', verbose_name='Требования к публикации'),
        ),
        migrations.AddField(
            model_name='conference_material',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tt', to='new.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='conference_material',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='new.Section', verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='conference_material',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Status_contact', verbose_name='Статус материала'),
        ),
        migrations.AddField(
            model_name='conference',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='new.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='conference',
            name='trebovania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new.Trebovania_public', verbose_name='Требования к публикации'),
        ),
        migrations.AddField(
            model_name='conference',
            name='year1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children2', to='new.Years', verbose_name='Год1'),
        ),
        migrations.AddField(
            model_name='conference',
            name='year2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children3', to='new.Years', verbose_name='Год2'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fotourl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new.Foto_user', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='new.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='new.Conference_material'),
        ),
    ]
