# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-09 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('im', models.CharField(max_length=200, verbose_name='Имя')),
                ('nameuse', models.CharField(max_length=200, verbose_name='Отчество')),
                ('telefon', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('organizac', models.CharField(max_length=200, verbose_name='Организация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
